[package]
name = "dwarf"
version = "0.0.1"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Decode DWARF debugging information"
repository = "https://github.com/philipc/rust-dwarf"
keywords = ["DWARF", "ELF"]
license = "MIT/Apache-2.0"

[dependencies]
byteorder = "0.5.3"
elf = "0.0.9"
